### ISSUE TITLE
Add MetalLB LoadBalancer Controller for ingress-nginx

### ISSUE THREAD

**Issue by runatyr1** [runatyr1/devops-cluster#35]
# Add MetalLB LoadBalancer for ingress-nginx

## Objective
Implement MetalLB to provide LoadBalancer service type support for the ingress-nginx controller in Hetzner Cloud environment.

## Requirements
- Deploy MetalLB using Helm
- Configure Layer2 mode for Hetzner Cloud networking
- Configure the LoadBalancer service for ingress-nginx
- Ensure proper firewall rules are in place
- Maintain existing security configurations

## Technical Specifications
- Use MetalLB v0.14.x
- Configure IP range from Hetzner Cloud network segment
- Update UFW rules to allow required MetalLB traffic
- Enable strict ARP mode in kube-proxy
- Add proper monitoring and health checks

## Acceptance Criteria
- [x] 1. MetalLB controller and speaker pods successfully deployed and running
- [x] 2. IP address pool correctly configured for Hetzner network
- [x] 3. ingress-nginx service type changed to LoadBalancer and accessible
- [x] 4. UFW rules updated to allow MetalLB and service traffic
- [x] 5. LoadBalancer services can be created and assigned external IPs

**Comment by runatyr1** [comment]
End to end test done, website on port 443 available via Metal-LB, added LoadBalancer service now available thanks to MetalLB:

```
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
```

![image](https://github.com/user-attachments/assets/0f19e788-cc3b-4886-96ce-12efe064fcba)
