### ISSUE TITLE
Demo: Implement Network Policy Isolation

### ISSUE THREAD

**Issue by runatyr1** [runatyr1/devops-cluster#58]
### Demo: Implement Network Policy Isolation

**Objective**: Practice creating & applying Kubernetes Network Policies to restrict pod-to-pod communication (CKS Exam Objective).

**Context**:  
Based on merged PRs, we've implemented runtime security (gVisor), RBAC hardening, and pod security contexts, but no explicit network policy enforcement exists yet.

**Tasks**:
- [ ] Create a `network-policy-demo` namespace
- [ ] Deploy 2 labeled pods: `frontend` (app=frontend) and `backend` (app=backend)
- [ ] Create a NetworkPolicy that:
  - Allows `frontend` pods to connect to `backend` on port 80
  - Blocks all other ingress to `backend` pods
- [ ] Validate with `kubectl exec` tests:
  - Confirm frontend can reach backend
  - Confirm external pods/namespaces cannot reach backend
  - Confirm backend cannot initiate connections to frontend

**Comment by runatyr1** [comment]
- All test passed, as expected only the front-end pod can communicate to back-end. 

Test file: https://github.com/runatyr1/devops-cluster/blob/a3088409ee808afd7654be865045f62422bb0e0c/scripts/tests/demo-network-policies.sh

user1@debian..:tests ✗$ ./demo-network-policies.sh 
➡ Running test: Frontend to backend
✅ Test passed (Got: 200)
➡ Running test: Same namespace external pod to backend
✅ Test passed (Got: 000)
➡ Running test: Default namespace pod to backend
✅ Test passed (Got: 000)
➡ Running test: Backend to frontend
✅ Test passed (Got: 000)
✅ All tests completed

**Comment by runatyr1** [comment]
- The network policy works by selecting the back-end pods, allowing incoming traffic only from frontend pods, and also only allowing outgoing traffic to DNS and itself. This will allow the frontend pod to initiate connection and traffic to flow in both directions, but the backend pod cannot initiate the connection (except for dns queries)

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-restrictions
  namespace: network-policy-demo
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - namespaceSelector: {}  # Allow DNS resolution
    ports:
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app: backend  # Allow self-communication
```
